class_name LiveEditCodec
extends RefCounted

## Live map edits (v0.2: the GM's terrain events during play, such as a bridge collapsing, a
## forest falling, fire, or a biome or terrain change with the authoring brushes): one
## AuthoringHistory entry's after side as a plain-value op that crosses the network as bytes,
## and back. A peer applies a decoded op through the same method the host's redo calls, on its
## own play-side AuthoringEditor, so its document ends as the host's by construction; derived
## geometry (terrain chunks, water, crossings, scatter) is rebuilt there. The probe that proved
## it (MapFingerprint and document equal for nine ops) is tests/unit/test_live_map_edits.gd.
##
## An op is {"v": VERSION, "kind": one of KINDS, "args": Array, "redo": bool}. Each kind goes
## through one method: "mask" AuthoringEditor.apply_mask_diff, "surface" apply_surface_diff,
## "props" set_prop_cell, "height" HeightEditor.apply_diff, "water" WaterEditor.apply_edit,
## "crossings" CrossingEditor.apply_list. One side of an entry travels: a redo (and a fresh
## record) its after side, diffs with their "after" blocks and records with their *_after
## fields; an undo its before side ("redo" false), diffs with their "before" blocks and records
## with their *_before fields, applied through the same method with redo false, so a kept
## rock goes back into the scatter and an allocated mask is dropped as the host's undo does.
## Both id lists of a diff travel either way (SurfaceStroke.changes_plants reads both). A props
## or crossings entry's undo is the same method with the before rows or list ("redo" true).
## Objects never travel (bytes_to_var refuses them): water bodies and crossings go in the
## document's JSON forms and come back through MapWaterIO's and MapCrossingIO's own readers.
##
## decode() reads the bytes as untrusted input: the byte cap before bytes_to_var, the version,
## kind and direction, then every argument (LiveEditReader); a fresh op is built from the
## checked values. Malformed bytes and ZSTD data that inflates past its rectangle are refused,
## but the engine prints an error first, so a receiver decodes at most one refused op a table
## (LiveEdits stops there) and only the host sends.
##
## Transport (NetworkGameSync). An op crosses in chunks of at most CHUNK_BYTES (chunks()),
## reassembled by an Assembler that refuses a run out of order or past MAX_BYTES; the sender's
## Outbox lets them leave at a capped rate, in order, since Steam drops reliable messages past
## about 512 KB queued and a whole-map sculpt at 200 ft is about 240 KB before ZSTD.
##
## Order and frame cost. apply() first finishes any height work an earlier op left spreading:
## a props op must see the rocks a sculpt kept, and cells regenerated by a later op must not be
## snapped again. So ops land in order on settled ground whoever calls it. A height or water op
## then queues its own ground work and returns; HeightEditor.step() drains it over frames
## within the editor's per-frame budgets. Queue does both for a peer: ops go in as they arrive,
## and step(), once a frame, applies the next one only when the last one's work has drained,
## at most one a frame. op_of() likewise finishes the host's height work first, since a
## sculpt's record is complete only once the rocks it keeps have landed.

const VERSION := 1
## Largest op decode() reads, and an Assembler puts together: a whole-map edit on the largest
## map with its props, well clear of any real one.
const MAX_BYTES := 4 * 1024 * 1024
## Largest chunk of an op on the wire.
const CHUNK_BYTES := 64 * 1024
## Most chunks one op takes (MAX_BYTES / CHUNK_BYTES).
const MAX_CHUNKS := 64
const KINDS: Array[String] = ["mask", "surface", "height", "water", "crossings", "props"]
## Kinds whose apply method takes the side to apply (redo true: after; false: before).
const SIDED: Array[String] = ["mask", "surface", "height", "water"]


## History entry `entry` ({"label", "undo", "redo"}) recorded by `editor` (the host's) as an
## op: its redo, or with `undo` its undo (see the header), or {} when that Callable is none of
## the methods above. Finishes the editor's height work first (see the header); called once
## that work is done, it costs nothing more.
static func op_of(entry: Dictionary, editor: AuthoringEditor, undo: bool = false) -> Dictionary:
	editor.finish_height_work()
	var action: Callable = entry.get("undo" if undo else "redo", Callable())
	if not action.is_valid():
		return {}
	var target := action.get_object()
	var args := action.get_bound_arguments()
	var key := String(action.get_method())
	if target is HeightEditor:
		key = "heights." + key
	elif target is WaterEditor:
		key = "water." + key
	elif target is CrossingEditor:
		key = "crossings." + key
	elif not target is AuthoringEditor:
		return {}
	match key:
		"apply_mask_diff":
			return _op("mask", [_diff_side(args[0], args[1])], args[1])
		"apply_surface_diff":
			return _op("surface", [_diff_side(args[0], args[1])], args[1])
		"set_prop_cell":
			return _op("props", [args[0], args[1]])
		"heights.apply_diff":
			var height_args := [_diff_side(args[0], args[1]), _record_side(args[2], args[1])]
			return _op("height", height_args, args[1])
		"water.apply_edit":
			var water_args := [_diff_side(args[0], args[1]), _record_side(args[2], args[1])]
			return _op("water", water_args, args[1])
		"crossings.apply_list":
			return _op("crossings", [_crossings_json(args[0]), args[1]])
	return {}


## `op` as bytes (no objects inside: op_of() turned them into their JSON forms).
static func encode(op: Dictionary) -> PackedByteArray:
	return var_to_bytes(op)


## `bytes` cut into the chunks that cross the network, each at most CHUNK_BYTES, in order.
static func chunks(bytes: PackedByteArray) -> Array[PackedByteArray]:
	var out: Array[PackedByteArray] = []
	for start in range(0, bytes.size(), CHUNK_BYTES):
		out.append(bytes.slice(start, start + CHUNK_BYTES))
	return out


## Reads untrusted `bytes` against `doc` (the receiving peer's document) and the palette under
## `palette_root`: {"op": a fresh op with water bodies and crossings rebuilt, ready for
## apply(), "problem": ""}, or {"op": {}, "problem": why it was refused}.
static func decode(
	bytes: PackedByteArray, doc: MapDocument, palette_root: String = PaletteLibrary.DEFAULT_ROOT
) -> Dictionary:
	if bytes.is_empty() or bytes.size() > MAX_BYTES:
		return _refused("%d bytes, outside 1..%d" % [bytes.size(), MAX_BYTES])
	var value: Variant = bytes_to_var(bytes)
	if not value is Dictionary:
		return _refused("not an op")
	var version: Variant = value.get("v")
	var kind: Variant = value.get("kind")
	var args: Variant = value.get("args")
	var redo: Variant = value.get("redo", true)
	if not version is int or version != VERSION:
		return _refused("not a version %d op" % VERSION)
	if not kind is String or not KINDS.has(kind) or not args is Array:
		return _refused("unknown kind, or no argument list")
	if not redo is bool or (not redo and not SIDED.has(kind)):
		return _refused("a direction this kind does not take")
	var reader := LiveEditReader.new(doc, palette_root)
	var checked := reader.read(kind, args, redo)
	if reader.problem != "":
		return _refused(reader.problem)
	return {"op": _op(kind, checked, redo), "problem": ""}


## Applies a decoded op to `editor` (the peer's) through the method the host's redo (or undo)
## calls, once the height work of any earlier op is done (see the header). A height or water
## op returns with its ground work queued for the editor's step_height_work().
static func apply(op: Dictionary, editor: AuthoringEditor) -> void:
	editor.finish_height_work()
	var args: Array = op.args
	var redo: bool = op.get("redo", true)
	match String(op.kind):
		"mask":
			editor.apply_mask_diff(args[0], redo)
		"surface":
			editor.apply_surface_diff(args[0], redo)
		"height":
			editor.heights.apply_diff(args[0], redo, args[1], true)
		"water":
			editor.water.apply_edit(args[0], redo, args[1], true)
		"crossings":
			editor.crossings.apply_list(args[0], args[1])
		"props":
			editor.set_prop_cell(args[0], args[1])


static func _op(kind: String, args: Array, redo: bool = true) -> Dictionary:
	return {"v": VERSION, "kind": kind, "args": args, "redo": redo}


static func _refused(why: String) -> Dictionary:
	return {"op": {}, "problem": why}


## "after" for the redo side, "before" for the undo side.
static func side_name(redo: bool) -> String:
	return "after" if redo else "before"


## A stroke diff (MaskStroke, SurfaceStroke, HeightStroke) with only the blocks of one side
## (`redo`: after, else before); {} for none (a water edit that carved nothing).
static func _diff_side(diff: Dictionary, redo: bool) -> Dictionary:
	if diff.is_empty():
		return {}
	var side := side_name(redo)
	var out := {}
	for key in diff:
		if key != "blocks" and key != "bytes":
			out[key] = diff[key]
	var blocks: Array = []
	for block: Dictionary in diff.get("blocks", []):
		blocks.append({"rect": block.rect, side: block[side]})
	out["blocks"] = blocks
	return out


## A sculpt or water edit record with only one side (`redo`: after, else before), objects as
## JSON forms. The kept rocks travel either way (RockKeeper.swap takes them out of the scatter
## on redo and puts them back on undo).
static func _record_side(record: Dictionary, redo: bool) -> Dictionary:
	var side := side_name(redo)
	var out := {"props_" + side: record.get("props_" + side, {}), "kept": record.get("kept", {})}
	var followed: Dictionary = record.get("crossings", {})
	out["crossings"] = (
		{} if followed.is_empty()
		else {side: _crossings_json(followed[side]), "area": followed.area}
	)
	if record.has("water_" + side):
		var model: Dictionary = record["water_" + side]
		var bodies: Array = []
		for body: WaterBody in model.get("bodies", []):
			bodies.append(MapWaterIO.body_json(body))
		out["water_" + side] = {
			"bodies": bodies, "pond_mask": model.pond_mask, "pond_size": model.pond_size
		}
		out["dressing_" + side] = record["dressing_" + side]
		out["region"] = record.region
	return out


static func _crossings_json(list: Array) -> Array:
	var out: Array = []
	for crossing: Crossing in list:
		out.append(MapCrossingIO.crossing_json(crossing))
	return out


## A peer's live edits for one editor, in arrival order (see the header): push() each payload,
## step() once a frame.
class Queue:
	extends RefCounted

	var editor: AuthoringEditor = null
	var _ops: Array[Dictionary] = []

	func _init(target: AuthoringEditor) -> void:
		editor = target

	## Decodes `bytes` against the editor's document and queues the op: "", or why it was
	## refused (nothing queued).
	func push(bytes: PackedByteArray) -> String:
		var decoded := LiveEditCodec.decode(bytes, editor.document, editor.palette_root)
		if decoded.problem == "":
			_ops.append(decoded.op)
		return decoded.problem

	## One frame: the editor's height work, or, on a frame that started with none, the next op.
	## True when an op was applied.
	func step() -> bool:
		var busy := editor.has_height_work()
		editor.step_height_work()
		if busy or _ops.is_empty():
			return false
		LiveEditCodec.apply(_ops.pop_front(), editor)
		return true

	## Every queued op applied in order and all their height work done, now: a late joiner's
	## catch-up, so its ground is edited before the tokens that follow it land (LiveEdits).
	func drain() -> void:
		while not _ops.is_empty():
			LiveEditCodec.apply(_ops.pop_front(), editor)
		editor.finish_height_work()

	## Ops waiting.
	func size() -> int:
		return _ops.size()

	## True when every op is applied and its height work is done.
	func is_idle() -> bool:
		return _ops.is_empty() and not editor.has_height_work()


## A receiver's reassembly of one op from its chunks (chunks()), which arrive in order on one
## reliable channel: part 0 starts an op, every later part must continue it, and the whole is
## returned once its last part is in. A part out of order, empty or past CHUNK_BYTES, a count
## past MAX_CHUNKS or a total past MAX_BYTES drops the op (`problem` says why).
class Assembler:
	extends RefCounted

	## Why the last part was refused, or "".
	var problem: String = ""

	var _key: int = 0
	var _index: int = -1
	var _parts: int = 0
	var _next: int = 0
	var _bytes := PackedByteArray()

	## Adds part `part` of `parts` of op `index` of table `key`: the op's bytes once whole,
	## else [] (more to come, or refused).
	func add(key: int, index: int, part: int, parts: int, data: PackedByteArray) -> PackedByteArray:
		problem = ""
		if part == 0:
			_reset()
			if parts < 1 or parts > LiveEditCodec.MAX_CHUNKS:
				return _refuse("an op of %d chunks" % parts)
			_key = key
			_index = index
			_parts = parts
		elif key != _key or index != _index or parts != _parts or part != _next:
			return _refuse("a chunk out of order")
		if data.is_empty() or data.size() > LiveEditCodec.CHUNK_BYTES:
			return _refuse("a chunk of %d bytes" % data.size())
		if _bytes.size() + data.size() > LiveEditCodec.MAX_BYTES:
			return _refuse("an op past %d bytes" % LiveEditCodec.MAX_BYTES)
		_bytes.append_array(data)
		_next += 1
		if _next < _parts:
			return PackedByteArray()
		var whole := _bytes
		_reset()
		return whole

	func _refuse(why: String) -> PackedByteArray:
		problem = why
		_reset()
		return PackedByteArray()

	func _reset() -> void:
		_key = 0
		_index = -1
		_parts = 0
		_next = 0
		_bytes = PackedByteArray()


## A sender's pacing: messages (a Callable that sends one, and its size in bytes) leave in
## the order they were pushed, at most `rate` bytes a second with a burst of one CHUNK_BYTES.
## A message of no bytes (a header, a callback) leaves as soon as every message before it has.
class Outbox:
	extends RefCounted

	## Bytes a second.
	var rate: int = 0

	var _budget: float = 0.0
	## [send Callable, bytes] in order.
	var _items: Array = []

	func _init(bytes_per_second: int) -> void:
		rate = bytes_per_second
		_budget = LiveEditCodec.CHUNK_BYTES

	## Queues `send` (one message of `bytes`) behind everything queued before it.
	func push(send: Callable, bytes: int) -> void:
		_items.append([send, mini(bytes, LiveEditCodec.CHUNK_BYTES)])

	## Adds `seconds` worth of budget and sends what it allows, in order: how many were sent.
	func drain(seconds: float) -> int:
		_budget = minf(_budget + rate * seconds, LiveEditCodec.CHUNK_BYTES)
		var sent := 0
		while not _items.is_empty() and _items[0][1] <= _budget:
			var item: Array = _items.pop_front()
			_budget -= item[1]
			(item[0] as Callable).call()
			sent += 1
		return sent

	## Messages waiting.
	func size() -> int:
		return _items.size()

	## Drops every waiting message (the connection is gone).
	func clear() -> void:
		_items.clear()
