class_name LiveEditCodec
extends RefCounted

## Live map edits (v0.2: the GM's terrain events during play, such as a bridge collapsing, a
## forest falling, fire, or a biome or terrain change with the authoring brushes): one
## AuthoringHistory entry's after side as a plain-value op that crosses the network as bytes,
## and back. A peer applies a decoded op through the same method the host's redo calls, on its
## own play-side AuthoringEditor, so its document ends as the host's by construction; derived
## geometry (terrain chunks, water, crossings, scatter) is rebuilt there. The probe that proved
## it (MapFingerprint and document equal for nine ops) is tests/unit/test_live_map_edits.gd.
##
## An op is {"v": VERSION, "kind": one of KINDS, "args": Array}. Each kind goes through one
## method: "mask" AuthoringEditor.apply_mask_diff, "surface" apply_surface_diff, "props"
## set_prop_cell, "height" HeightEditor.apply_diff, "water" WaterEditor.apply_edit, "crossings"
## CrossingEditor.apply_list. Only the after side travels: diffs keep their "after" blocks,
## records their *_after fields, surface diffs their ids_before too (SurfaceStroke
## .changes_plants reads both lists); an undo is the before side, sent as one more op. Objects
## never travel (bytes_to_var refuses them): water bodies and crossings go in the document's
## JSON forms and come back through MapWaterIO's and MapCrossingIO's own readers and rules.
##
## decode() reads the bytes as untrusted input: the byte cap before bytes_to_var, the version
## and kind, then every argument (LiveEditReader); a fresh op is built from the checked values.
## Malformed bytes and ZSTD data that inflates past its rectangle are refused, but the engine
## prints an error first, so a sender must be rate-limited.
##
## Order and frame cost. apply() first finishes any height work an earlier op left spreading:
## a props op must see the rocks a sculpt kept, and cells regenerated by a later op must not be
## snapped again. So ops land in order on settled ground whoever calls it. A height or water op
## then queues its own ground work and returns; HeightEditor.step() drains it over frames
## within the editor's per-frame budgets. Queue does both for a peer: ops go in as they arrive,
## and step(), once a frame, applies the next one only when the last one's work has drained,
## at most one a frame. op_of() likewise finishes the host's height work first, since a
## sculpt's record is complete only once the rocks it keeps have landed.

const VERSION := 1
## Largest payload decode() reads. Steam drops reliable messages past about 512 KB queued; a
## channel would chunk anything bigger.
const MAX_BYTES := 256 * 1024
const KINDS: Array[String] = ["mask", "surface", "height", "water", "crossings", "props"]


## The after side of history entry `entry` ({"label", "undo", "redo"}) recorded by `editor` (the
## host's) as an op, or {} when its redo is none of the methods above. Finishes the editor's
## height work first (see the header); called once that work is done, it costs nothing more.
static func op_of(entry: Dictionary, editor: AuthoringEditor) -> Dictionary:
	editor.finish_height_work()
	var redo: Callable = entry.get("redo", Callable())
	if not redo.is_valid():
		return {}
	var target := redo.get_object()
	var args := redo.get_bound_arguments()
	var key := String(redo.get_method())
	if target is HeightEditor:
		key = "heights." + key
	elif target is WaterEditor:
		key = "water." + key
	elif target is CrossingEditor:
		key = "crossings." + key
	elif not target is AuthoringEditor:
		return {}
	match key:
		"apply_mask_diff":
			return _op("mask", [_diff_after(args[0])])
		"apply_surface_diff":
			return _op("surface", [_diff_after(args[0])])
		"set_prop_cell":
			return _op("props", [args[0], args[1]])
		"heights.apply_diff":
			return _op("height", [_diff_after(args[0]), _record_after(args[2])])
		"water.apply_edit":
			return _op("water", [_diff_after(args[0]), _record_after(args[2])])
		"crossings.apply_list":
			return _op("crossings", [_crossings_json(args[0]), args[1]])
	return {}


## `op` as bytes (no objects inside: op_of() turned them into their JSON forms).
static func encode(op: Dictionary) -> PackedByteArray:
	return var_to_bytes(op)


## Reads untrusted `bytes` against `doc` (the receiving peer's document) and the palette under
## `palette_root`: {"op": a fresh op with water bodies and crossings rebuilt, ready for
## apply(), "problem": ""}, or {"op": {}, "problem": why it was refused}.
static func decode(
	bytes: PackedByteArray, doc: MapDocument, palette_root: String = PaletteLibrary.DEFAULT_ROOT
) -> Dictionary:
	if bytes.is_empty() or bytes.size() > MAX_BYTES:
		return _refused("%d bytes, outside 1..%d" % [bytes.size(), MAX_BYTES])
	var value: Variant = bytes_to_var(bytes)
	if not value is Dictionary:
		return _refused("not an op")
	var version: Variant = value.get("v")
	var kind: Variant = value.get("kind")
	var args: Variant = value.get("args")
	if not version is int or version != VERSION:
		return _refused("not a version %d op" % VERSION)
	if not kind is String or not KINDS.has(kind) or not args is Array:
		return _refused("unknown kind, or no argument list")
	var reader := LiveEditReader.new(doc, palette_root)
	var checked := reader.read(kind, args)
	if reader.problem != "":
		return _refused(reader.problem)
	return {"op": _op(kind, checked), "problem": ""}


## Applies a decoded op to `editor` (the peer's) through the method the host's redo calls, once
## the height work of any earlier op is done (see the header). A height or water op returns
## with its ground work queued for the editor's step_height_work().
static func apply(op: Dictionary, editor: AuthoringEditor) -> void:
	editor.finish_height_work()
	var args: Array = op.args
	match String(op.kind):
		"mask":
			editor.apply_mask_diff(args[0], true)
		"surface":
			editor.apply_surface_diff(args[0], true)
		"height":
			editor.heights.apply_diff(args[0], true, args[1], true)
		"water":
			editor.water.apply_edit(args[0], true, args[1], true)
		"crossings":
			editor.crossings.apply_list(args[0], args[1])
		"props":
			editor.set_prop_cell(args[0], args[1])


static func _op(kind: String, args: Array) -> Dictionary:
	return {"v": VERSION, "kind": kind, "args": args}


static func _refused(why: String) -> Dictionary:
	return {"op": {}, "problem": why}


## A stroke diff (MaskStroke, SurfaceStroke, HeightStroke) without its before blocks; {} for
## none (a water edit that carved nothing).
static func _diff_after(diff: Dictionary) -> Dictionary:
	if diff.is_empty():
		return {}
	var out := {}
	for key in diff:
		if key != "blocks" and key != "bytes":
			out[key] = diff[key]
	var blocks: Array = []
	for block: Dictionary in diff.get("blocks", []):
		blocks.append({"rect": block.rect, "after": block.after})
	out["blocks"] = blocks
	return out


## A sculpt or water edit record without its before sides, objects as JSON forms.
static func _record_after(record: Dictionary) -> Dictionary:
	var out := {"props_after": record.get("props_after", {}), "kept": record.get("kept", {})}
	var followed: Dictionary = record.get("crossings", {})
	out["crossings"] = (
		{} if followed.is_empty()
		else {"after": _crossings_json(followed.after), "area": followed.area}
	)
	if record.has("water_after"):
		var model: Dictionary = record.water_after
		var bodies: Array = []
		for body: WaterBody in model.get("bodies", []):
			bodies.append(MapWaterIO.body_json(body))
		out["water_after"] = {
			"bodies": bodies, "pond_mask": model.pond_mask, "pond_size": model.pond_size
		}
		out["dressing_after"] = record.dressing_after
		out["region"] = record.region
	return out


static func _crossings_json(list: Array) -> Array:
	var out: Array = []
	for crossing: Crossing in list:
		out.append(MapCrossingIO.crossing_json(crossing))
	return out


## A peer's live edits for one editor, in arrival order (see the header): push() each payload,
## step() once a frame.
class Queue:
	extends RefCounted

	var editor: AuthoringEditor = null
	var _ops: Array[Dictionary] = []

	func _init(target: AuthoringEditor) -> void:
		editor = target

	## Decodes `bytes` against the editor's document and queues the op: "", or why it was
	## refused (nothing queued).
	func push(bytes: PackedByteArray) -> String:
		var decoded := LiveEditCodec.decode(bytes, editor.document, editor.palette_root)
		if decoded.problem == "":
			_ops.append(decoded.op)
		return decoded.problem

	## One frame: the editor's height work, or, on a frame that started with none, the next op.
	## True when an op was applied.
	func step() -> bool:
		var busy := editor.has_height_work()
		editor.step_height_work()
		if busy or _ops.is_empty():
			return false
		LiveEditCodec.apply(_ops.pop_front(), editor)
		return true

	## Ops waiting.
	func size() -> int:
		return _ops.size()

	## True when every op is applied and its height work is done.
	func is_idle() -> bool:
		return _ops.is_empty() and not editor.has_height_work()
